### ISSUE TITLE
Index each polygon individually rather than the container bounding box?

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-rtree#1]
Consider the United States

**Comment by nvkelso** [comment]
Each part in the multipart polygon?

**Comment by thisisaaronland** [comment]
Yes – the same "place" (say a country) gets indexed multiple times, storing a bounding box for each outer ring in a (multi) polygon rather than the bounding box of the entire set.

This is useful when testing for breaches since otherwise the original bounding box intersecting bounding box query (using the R tree) will return an excessive number of false positives, particularly at the country level which then require parsing often very large coastlines to no avail.

This has actually been done now so closing this ticket:

https://github.com/whosonfirst/go-whosonfirst-rtree/blob/multi/rtree.go#L82-L101
